export const arcVaultAbi = [
  {
    type: 'function',
    name: 'createVault',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'goalAmount', type: 'uint256' },
      { name: 'unlockTime', type: 'uint256' },
    ],
    outputs: [{ name: 'vaultId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'deposit',
    stateMutability: 'payable',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getVault',
    stateMutability: 'view',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'name', type: 'string' },
          { name: 'goalAmount', type: 'uint256' },
          { name: 'balance', type: 'uint256' },
          { name: 'unlockTime', type: 'uint256' },
          { name: 'closed', type: 'bool' },
          { name: 'createdAt', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getUserVaultIds',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
  },
  {
    type: 'function',
    name: 'isWithdrawable',
    stateMutability: 'view',
    inputs: [{ name: 'vaultId', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'event',
    name: 'VaultCreated',
    inputs: [
      { name: 'vaultId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'goalAmount', type: 'uint256', indexed: false },
      { name: 'unlockTime', type: 'uint256', indexed: false },
    ],
  },
] as const

export const arcCircleAbi = [
  {
    type: 'function',
    name: 'createCircle',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'contributionAmount', type: 'uint256' },
      { name: 'maxMembers', type: 'uint256' },
    ],
    outputs: [{ name: 'circleId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'joinCircle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'contribute',
    stateMutability: 'payable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimPayout',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCircle',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'name', type: 'string' },
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'maxMembers', type: 'uint256' },
          { name: 'memberCount', type: 'uint256' },
          { name: 'currentRound', type: 'uint256' },
          { name: 'pot', type: 'uint256' },
          { name: 'active', type: 'bool' },
          { name: 'started', type: 'bool' },
          { name: 'createdAt', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getMembers',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'hasContributed',
    stateMutability: 'view',
    inputs: [
      { name: 'circleId', type: 'uint256' },
      { name: 'round', type: 'uint256' },
      { name: 'member', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getRoundContributionCount',
    stateMutability: 'view',
    inputs: [
      { name: 'circleId', type: 'uint256' },
      { name: 'round', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'isMember',
    stateMutability: 'view',
    inputs: [
      { name: 'circleId', type: 'uint256' },
      { name: 'account', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'currentRecipient',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'nextCircleId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'CircleCreated',
    inputs: [
      { name: 'circleId', type: 'uint256', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'contributionAmount', type: 'uint256', indexed: false },
      { name: 'maxMembers', type: 'uint256', indexed: false },
    ],
  },
] as const
